# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba37901e4140093afc7e8b87c95b89175b9176d3307a6e23098b53b770d6cc4a61be0c02b30821d60874539d9b0033a15ebd049fe0f2441a0226b7de59154dbe

test:
  secret_key_base: 908c8220bfdaa1fb4464c19643886cd02da6bfe209e081d98c614747716a30c7c4490fe593f96846dbcdeff4b66fc07cc281f1fb00d1958c6dbe915ad3866de9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
